def patterncount(text, pattern):
    br = 0
    for i in range(0, (len(text) - len(pattern))+1):
        if (text[i:i + len(pattern)] == pattern):
            br += 1

    return br


if __name__ == "__main__":
    #text = "TGTTAGGAAGTTAGGATGACAGTACGTTAGGAGTTAGGAGTTAGGAGTTAAGTTAGGAAAAGGGGTTAGGAGCGTTAGGACCAAAGTTAGGAAAACCGGTGTTAGGATTCGTTAGGATGGTTAGGACGCATTGTTAGGAGTTAGGAACTCCAAACCCATGTTAGGAGTTAGGACGTTAGGACGAAGCGGTTAGGAAAAGGTTAGGATGTTAGGACGTTAGGAAAAGGTTGTTAGGAGTTAGGATAATGTTAGGAGAGTTTCGGGTTAGGAGGCTCGTTAGGAGTTAGGAATGTTAGGATGTTAGGACAACAGTGTTAGGAAACTTGGTTAGGAGTTAGGAGGTTAGGAGTTAGGAGTTAGGAGTTAGGAAACGTTAGGAGGTGGTTAGGACGGGGTTAGGATGCGATGTTAGGAGTTAGGATGTTAGGAGTGTTAGGAGCGCGTTAGGAGGCTGTTAGGAGTTAGGATGGTTAGGAAATGTTAGGACTAGAATGTTAGGATAGCCAGTTAGGATGTTAGGAGTTAGGACTTGTTAGGACCGTTAGGAGCCCAGTTAGGAGTTAGGAGTTAGGAAGTCTTCGGTTAGGAGTTAGGAGTTAGGAGTTAGGAGTTAGGAAACGTTAGGATTGATGTTAGGAGTTAGGATTGTTAGGATCCGATTTGCGTTAGGAGAGATAAGTTAGGAGTTAGGAGGGTTAGGAGTTAGGAGTTAGGAGTGTTAGGAATCCTCGCTACTGTTAGGATCTGTTAGGAGTTAGGAGTAGACTCGTTAGGAGGTGTAGTTAGGATTTGCTTGTTAGGAGTTAGGAGTTAGGAGTTAGGAGGTTAGGAAACGGTTAGGATGGTTAGGAGTTAGGAGGAACAGAGTGTTAGGAAGTTAGGATGTAGTTAGGAGTTAGGAAGTTAGGAGTTAGGACACGGGGTTAGGACTCTGTTAGGACAGGGATCGGTTAGGATACCGGTTAGGAAGCGAGTTAGGACGGGTTAGGATAGTAGTTAGGA"
    #pattern ="GTTAGGAGT"
    text="GCGCG"
    pattern="GCG"
    res = patterncount(text, pattern)
    print(res)